### DISCUSSION TITLE
yaml file example for L2 testing validation based on platform.

### DISCUSSION THREAD

**Discussion by Ulrond** [rdkcentral/rdkb-halif-test-emmc#3] [Ideas]
Assumg you wanted to validate based on platform the values from this structure.

Referring to [Key-Value-Pair-Assertions-for-Unit-Testing](https://github.com/rdkcentral/ut-core/wiki/ut_kvp_profile:-Key%E2%80%90Value-Pair-Assertions-for-Unit-Testing)

```c
typedef struct _stmgr_DiagnosticsAttributes {
    char m_name[RDK_STMGR_MAX_STRING_LENGTH];   /*!< To store the name of the SMART (Self-Monitoring, Analysis, and Reporting Technology) diagnostic attribute. The name provides a way to identify the attribute. */
    char m_value[RDK_STMGR_MAX_STRING_LENGTH];  /*!< To store the value of the SMART diagnostic attribute. The value is represented as a comma-separated string, which may contain multiple pieces of information related to the attribute. */
} eSTMGRDiagAttributes;
...
typedef struct _stmgr_DiagnosticsAttributeList {
    unsigned short m_numOfAttributes;                                        /**< It holds the count of how many attributes are stored in the m_diagnostics array. */
    eSTMGRDiagAttributes m_diagnostics[RDK_STMGR_MAX_DIAGNOSTIC_ATTRIBUTES]; /**< Each element of this array represents a diagnostic attribute.  */
} eSTMGRDiagAttributesList;
...
typedef struct _stmgr_Health {
    char m_deviceID[RDK_STMGR_MAX_STRING_LENGTH];               /**< This is an array of characters with a size defined by RDK_STMGR_MAX_STRING_LENGTH. It is used to store the unique identifier or serial number of the EMMC device. The identifier is vendor-specific and is a 128-byte character array. */														 
    eSTMGRDeviceType m_deviceType;                              /**< This member is of type eSTMGRDeviceType and represents the type of the EMMC device, such as HDD, SDCARD, USB, etc. The eSTMGRDeviceType is an enumerated datatype that defines different possible device types. */															 
    bool m_isOperational;                                       /**< This is a boolean variable that indicates whether the device is operational. Possible values are true (operational) or false (not operational). */
    bool m_isHealthy;                                           /**< This is a boolean variable that indicates whether the device is healthy. Possible values are true (healthy) or false (not healthy). */
    union {
        eSTMGRDiagAttributesList m_list;                        																	
        char m_blob[RDK_STMGR_DIAGNOSTICS_BLOB_LENGTH];         
    } m_diagnostics;                                             /**< This is a union that can hold either an object of type eSTMGRDiagAttributesList (named m_list) or a character array named m_blob with a size defined by RDK_STMGR_DIAGNOSTICS_BLOB_LENGTH (2048 bytes). The m_list object is used to store diagnostic attributes, while m_blob is a vendor-specific diagnostic information array. */
    eSTMGRDiagAttributesList m_lifetimesList;                    /**< This object is of type eSTMGRDiagAttributesList and is used to store a list of attributes related to the lifetimes of the device. */
    eSTMGRDiagAttributesList m_firstExceededConfiguredLife;      /**< This object is of type eSTMGRDiagAttributesList and is used to store attributes related to the first time the device exceeded its configured lifetime. */	 
    eSTMGRDiagAttributesList m_firstExceededMaxLife;             /**< This object is of type eSTMGRDiagAttributesList and is used to store attributes related to the first time the device exceeded its maximum lifetime. */																 
    eSTMGRDiagAttributesList m_healthStatesList;                 /**< This object is of eSTMGRDiagAttributesList and is used to store a list of attributes related to the health states of the device. */
} eSTMGRHealthInfo;
```

Here's an example of a rough definition for a specific platform, you can have as many `.yaml`  files as you like configured as required to validate the expected data.

Since the values of the data may differ, you may want to include range checks rather than specific values.

## platformA.yaml

```yaml
emmc:
    health:
        0:
            m_deviceID: "HDD ID"
                # RDK_STMGR_DEVICE_TYPE_HDD   = 0,    /**< Device type is HDD. */
                # RDK_STMGR_DEVICE_TYPE_SDCARD = 1,   /**< Device type is SD Card. */
                # RDK_STMGR_DEVICE_TYPE_USB = 2,      /**< Device type is USB. */
                # RDK_STMGR_DEVICE_TYPE_FLASH = 3,    /**< Device type is Flash. */
                # RDK_STMGR_DEVICE_TYPE_NVRAM = 4,    /**< Device type is NVRAM. */
                # RDK_STMGR_DEVICE_TYPE_EMMCCARD = 5, /**< Device type is eMMC Card. */
                # RDK_STMGR_DEVICE_TYPE_MAX = 6       /**< Device type is Max. */
            m_deviceType: "RDK_STMGR_DEVICE_TYPE_EMMCCARD"
            m_isOperational: true
            m_isHealthy: true
                m_blob: false
                m_list:
                        0:
                            m_name: "item a"
                            m_value: "0x1234"
                m_lifetimesList:
                        0:
                            m_name: "lifetimes1"
                            m_value: "0x1234"
                m_firstExceededConfiguredLife:
                        0:
                            m_name: "ExceededConfiguredLifeCount"
                            m_value: "0x1234"
                m_firstExceededMaxLife:
                        0:
                            m_name: "ExceededMax"
                            m_value: "0x1234"
                m_healthStatesList:
                        0:
                            m_name: "healthStates"
                            m_value: "0x1234"
        1:
            m_deviceID: "EMMCCard ID"
                # RDK_STMGR_DEVICE_TYPE_HDD   = 0,    /**< Device type is HDD. */
                # RDK_STMGR_DEVICE_TYPE_SDCARD = 1,   /**< Device type is SD Card. */
                # RDK_STMGR_DEVICE_TYPE_USB = 2,      /**< Device type is USB. */
                # RDK_STMGR_DEVICE_TYPE_FLASH = 3,    /**< Device type is Flash. */
                # RDK_STMGR_DEVICE_TYPE_NVRAM = 4,    /**< Device type is NVRAM. */
                # RDK_STMGR_DEVICE_TYPE_EMMCCARD = 5, /**< Device type is eMMC Card. */
                # RDK_STMGR_DEVICE_TYPE_MAX = 6       /**< Device type is Max. */
            m_deviceType: "RDK_STMGR_DEVICE_TYPE_HDD"
            m_isOperational: false
            m_isHealthy: false
            m_blob: true
                value: "Some blob data is present"
```

```c
ut_control_keyStringMapping_t deviceTypeTable[] = 
{
    {"RDK_STMGR_DEVICE_TYPE_HDD", (int32_t)RDK_STMGR_DEVICE_TYPE_HDD},
    {"RDK_STMGR_DEVICE_TYPE_SDCARD", (int32_t)RDK_STMGR_DEVICE_TYPE_SDCARD},
    {"RDK_STMGR_DEVICE_TYPE_USB", (int32_t)RDK_STMGR_DEVICE_TYPE_USB},
    {"RDK_STMGR_DEVICE_TYPE_FLASH", (int32_t)RDK_STMGR_DEVICE_TYPE_FLASH},
    {"RDK_STMGR_DEVICE_TYPE_NVRAM", (int32_t)RDK_STMGR_DEVICE_TYPE_NVRAM},
    {"RDK_STMGR_DEVICE_TYPE_EMMCCARD", (int32_t)RDK_STMGR_DEVICE_TYPE_EMMCCARD},
    {"RDK_STMGR_DEVICE_TYPE_MAX", (int32_t)RDK_STMGR_DEVICE_TYPE_MAX},
    {NULL, (int32_t)0}
};

const char* healthHeader="emmc.health";
int listCount = UT_KVP_PROFILE_GET_LIST_COUNT(healthHeader);

...
for (int i=0; i< listCount; i++ )
{
    char *healthIndex[UT_KVP_MAX_ELEMENT_SIZE];
   char *deviceTypeString
   eSTMGRDeviceType deviceType;
    sprintf( healthIndex, "%s.%d.m_deviceType", healthHeader, i );
    m_deviceTypeString = UT_KVP_PROFILE_GET_STRING( healthIndex );
    deviceType = (eSTMGRDeviceType)UT_Control_GetMapValue ( deviceTypeTable, m_deviceTypeString, RDK_STMGR_DEVICE_TYPE_MAX ));
  switch deviceType)
   case RDK_STMGR_DEVICE_TYPE_HDD;
   case RDK_STMGR_DEVICE_TYPE_SDCARD;
   case RDK_STMGR_DEVICE_TYPE_MAX;

}
..

## platformB.yml
